Add Transform component to the pipeline
deep-diver/semantic-segmentation-ml-pipeline pull request #29
Opened 2022-09-23 06:58 UTC by deep-diver

This PR includes the following **changes**:
- `tfx-pipeline.ipynb`: modified to demonstrate how `Transform` can be integrated into the pipeline
- `preprocessing.py`: handle low-resolution data preprocessing
- `preprocessing_full_res.py`: handle full-resolution data preprocessing
- `model.py` and `model_full_res.py`: replaced `parse_tfr` and `preprocess` steps from the previous version with transformed dataset from `Transform`
- `local_pipeline.py`: `Transform` component is added to the local pipeline
- `pipeline.py`: `Transform` component is added to the Vertex pipeline. Also, there is a condition to run `Transform` component in Dataflow
- `configs.py`: replace data source path to the re-generated TFRecords for the low-resolution dataset

**Note:** In order to use `Transform`, we need `StatisticsGen` and `SchemaGen`, so they are added to the pipeline as well.

**Note:** This code changes are verified to work on local and Vertex environment.

2022-09-23 07:01 UTC, sayakpaul commented
@deep-diver the low-res PR is a dependency of this PR, right? Let's please hold off until it gets resolved.

2022-09-26 04:04 UTC, deep-diver commented
@sayakpaul  

this is up for the review as well!

2022-09-26 05:23 UTC, sayakpaul commented on training_pipeline/models/model.py
> +        tf_transform_output.transformed_metadata.schema,
Let's add informative comments here:

* How `Transform` is being used.
* How it's inferring the TFRecord schema

Anything that would help the reader read the code better.

2022-09-26 05:36 UTC, sayakpaul requested changes
@deep-diver looking good. I suggest we add a diagram that shows how the scripts in this PR are inter connected. That will help the readers navigate the code better. 

WDYT?

2022-09-26 05:36 UTC, sayakpaul commented on training_pipeline/models/model.py
> +    )
128 should be defined as a meaningful variable.

2022-09-26 05:36 UTC, sayakpaul commented on training_pipeline/models/model.py
> +        metrics=["sparse_categorical_accuracy"],
If you supply `accuracy` Keras will automatically infer the appropriate variant.

2022-09-26 05:36 UTC, sayakpaul commented on training_pipeline/models/model.py
>  def _input_fn(
Also denote what `_input_fn` is responsible of in this context.

2022-09-26 05:36 UTC, sayakpaul commented on training_pipeline/models/model.py
> +    )
Also, I was thinking maybe the model architecture should live in a separate module and we could then call this script something like `train.py`. Calling it `model.py` is vague IMO. 

WDYT?

2022-09-26 07:03 UTC, deep-diver commented
@sayakpaul 

addressed your comments!
thanks for the great comments. I really like them 👍🏼

2022-09-26 12:49 UTC, deep-diver commented
@sayakpaul 

fixed the broken parts, and it is verified to be working properly.

<p align="center">
<img height="400" alt="Screen Shot 2022-09-26 at 9 47 23 PM" src="https://user-images.githubusercontent.com/26025527/192280400-6a646b61-7c22-402e-bd20-74dd55ff8dbc.png">
</p>

2022-09-27 02:01 UTC, sayakpaul approved these changes

2022-09-27 02:08 UTC, merged