refactoring into smaller piecies
deep-diver/semantic-segmentation-ml-pipeline pull request #31
Opened 2022-09-27 04:50 UTC by deep-diver

decouple files under `model` directory

- `common.py` to define common variables like key names (i.e. `IMAGE_KEY`)
- `utils.py` to define common utility function like log and `transformed_key`
- `hyperparams.py` to define a set of default hyperparameters
- `signatures.py` to define the signature for the `serving_default`.

2022-09-27 11:59 UTC, sayakpaul requested changes
Nice work! Could you add a README or brief descriptions at the top of each of the individual scripts to denote what they're responsible for doing?

2022-09-27 11:59 UTC, sayakpaul commented on training_pipeline/models/signatures.py
> +    decoded = decoded / 255
Let's use `mobilenet_v2.preprocess_input()` for consistency.

2022-09-27 11:59 UTC, sayakpaul commented on training_pipeline/models/signatures.py
> +    return serving_fn
Nice 🔥

2022-09-27 12:36 UTC, deep-diver commented
> Nice work! Could you add a README or brief descriptions at the top of each of the individual scripts to denote what they're responsible for doing?

Absolutely!

2022-09-27 13:13 UTC, deep-diver commented
@sayakpaul 

addressed your comment :)

2022-09-28 03:03 UTC, sayakpaul approved these changes
Excellent update.

2022-09-28 03:05 UTC, merged